[project]
name = "customer-valgroup-ragchat-qdrant-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.32.0",
    "requests>=2.31.0",
    "python-dotenv>=1.0.1",
    "boto3>=1.38.6",
]
